//
// Created by rogan2 on 19/11/2020.
//


#define HEADERTECH_LOGGING_IMPL 1
#define HEADERTECH_PROFILER_IMPL 1
#define HEADERTECH_EVENTS_IMPL 1
#define HEADERTECH_CONFIG_IMPL 1
#define HEADERTECH_RENDER_IMPL 1
#define HEADERTECH_WINDOW_IMPL 1
#define HEADERTECH_CORE_IMPL 1
#define DEFINE_IMPLEMENTATION 1

#include <WindowIncludes.h>
