set(FMT_PEDANTIC OFF CACHE INTERNAL "" FORCE)
set(FMT_WERROR ON CACHE INTERNAL "" FORCE)
set(FMT_DOC OFF CACHE INTERNAL "" FORCE)
set(FMT_INSTALL OFF CACHE INTERNAL "" FORCE)
set(FMT_TEST OFF CACHE INTERNAL "" FORCE)
set(FMT_FUZZ OFF CACHE INTERNAL "" FORCE)
set(FMT_CUDA_TEST OFF CACHE INTERNAL "" FORCE)
set(FMT_OS ON CACHE INTERNAL "" FORCE)
add_subdirectory(fmt/ EXCLUDE_FROM_ALL)

# lib fmt::fmt