#set(BUILD_SHARED_LIBS ON CACHE INTERNAL "" FORCE)
#set(BUILD_STATIC_LIBS OFF CACHE INTERNAL "" FORCE)
#set(GLM_TEST_ENABLE OFF CACHE INTERNAL "" FORCE)
#set(GLM_TEST_ENABLE_CXX_17 ON CACHE INTERNAL "" FORCE)
#set(GLM_TEST_ENABLE_LANG_EXTENSIONS ON CACHE INTERNAL "" FORCE)
#set(GLM_TEST_ENABLE_SIMD_SSE2 ON CACHE INTERNAL "" FORCE)
add_subdirectory(glm/ EXCLUDE_FROM_ALL)

RegisterLibrary(glm INTERFACE OFF)
RegisterLibrary(glm_shared PRIVATE OFF)

# lib glm::glm
