set(BUILD_SHARED_LIBS ON CACHE INTERNAL "" FORCE)
set(HTTPLIB_USE_OPENSSL_IF_AVAILABLE OFF CACHE INTERNAL "" FORCE)
set(HTTPLIB_USE_ZLIB_IF_AVAILABLE ON CACHE INTERNAL "" FORCE)
set(HTTPLIB_REQUIRE_OPENSSL OFF CACHE INTERNAL "" FORCE)
set(HTTPLIB_REQUIRE_ZLIB OFF CACHE INTERNAL "" FORCE)
set(HTTPLIB_USE_BROTLI_IF_AVAILABLE ON CACHE INTERNAL "" FORCE)
set(HTTPLIB_REQUIRE_BROTLI OFF CACHE INTERNAL "" FORCE)
set(HTTPLIB_COMPILE ON CACHE INTERNAL "" FORCE)
set(BROTLI_USE_STATIC_LIBS OFF CACHE INTERNAL "" FORCE)
set(OPENSSL_USE_STATIC_LIBS OFF CACHE INTERNAL "" FORCE)
add_subdirectory(httplib/ EXCLUDE_FROM_ALL)

RegisterLibrary(httplib PRIVATE OFF)

# lib httplib::httplib
