set(SPDLOG_BUILD_ALL OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_SHARED ON CACHE INTERNAL "" FORCE)
set(SPDLOG_ENABLE_PCH ON CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_EXAMPLE OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_EXAMPLE_HO OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_TESTS OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_TESTS_HO OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_BENCH OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_SANITIZE_ADDRESS OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_BUILD_WARNINGS ON CACHE INTERNAL "" FORCE)
set(SPDLOG_INSTALL OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_FMT_EXTERNAL ON CACHE INTERNAL "" FORCE)
set(SPDLOG_FMT_EXTERNAL_HO OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_NO_EXCEPTIONS ON CACHE INTERNAL "" FORCE)

if (WIN32)
    set(SPDLOG_WCHAR_SUPPORT OFF CACHE INTERNAL "" FORCE)
    set(SPDLOG_WCHAR_FILENAMES OFF CACHE INTERNAL "" FORCE)
endif ()
if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    set(SPDLOG_CLOCK_COARSE OFF CACHE INTERNAL "" FORCE)
endif ()

set(SPDLOG_PREVENT_CHILD_FD OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_NO_THREAD_ID OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_NO_TLS OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_NO_ATOMIC_LEVELS OFF CACHE INTERNAL "" FORCE)
set(SPDLOG_DISABLE_DEFAULT_LOGGER ON CACHE INTERNAL "" FORCE)
set(SPDLOG_TIDY OFF CACHE INTERNAL "" FORCE)

add_subdirectory(spdlog/ EXCLUDE_FROM_ALL)

set_property(
        TARGET spdlog
        PROPERTY UNITY_BUILD OFF
)

RegisterLibrary(spdlog PRIVATE)

# lib spdlog::spdlog
