option(BUILD_FILE "")
option(NAME "")
option(CONFIG "")
option(HEADER_OUTPUT "")
option(SOURCE_OUTPUT "")
option(HEADER_INPUT "")
option(SOURCE_INPUT "")
option(RC_INPUT "")
option(RC_OUTPUT "")
option(MAJOR "")
option(MINOR "")
option(PATCH "")
option(TWEAK "")
string(TIMESTAMP BUILD_TIMESTAMP "%s" UTC)

file(READ ${BUILD_FILE} BUILD_NUMBER)

configure_file(${HEADER_INPUT} ${HEADER_OUTPUT} @ONLY NEWLINE_STYLE UNIX)
configure_file(${SOURCE_INPUT} ${SOURCE_OUTPUT} @ONLY NEWLINE_STYLE UNIX)
configure_file(${RC_INPUT} ${RC_OUTPUT} @ONLY NEWLINE_STYLE WIN32)