name: CMake

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build HeaderTech.${{ matrix.build_type }} (${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        build_type: [Debug, Release]
    runs-on: ${{ matrix.os }}

    outputs:
      binary: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}/bin

    env:
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_DIR: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}

    steps:
      - uses: BSFishy/pip-action@v1
        with:
          packages: Jinja2<3.0

      - name: MacOS Tools
        if: matrix.os == 'macos-latest'
        run: brew install mercurial

      - name: Ubuntu Tools
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install xorg-dev clang

      - name: Windows Tools
        if: matrix.os == 'windows-latest'
        run: echo "Windows"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: submodules-init
        uses: snickerbockers/submodules-init@v4

      - name: Clone PhysFS
        run: hg clone https://hg.icculus.org/icculus/physfs/ ext/physfs

      - name: Apply Patches
        shell: bash
        run: |
          git apply --apply patches/glad.patch
          git apply --apply patches/ctti.patch
          git apply --apply patches/fmt.patch

      - name: Create Build Environment
        shell: bash
        run: cmake -E make_directory $BUILD_DIR

      - name: Configure CMake Windows
        shell: bash
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..

      - name: Configure CMake Ubuntu
        shell: bash
        if: matrix.os == 'ubuntu-20.04'
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
        working-directory: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-fpermissive ..

      - name: Configure CMake MacOS
        shell: bash
        if: matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}
        run: |
          export CC=$(brew --prefix llvm)/bin/clang
          export CXX=$(brew --prefix llvm)/bin/clang++
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-fpermissive ..

      - name: Build Windows
        shell: bash
        if: matrix.os == 'windows-latest'
        working-directory: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}
        run: cmake --build . --config $BUILD_TYPE --target Editor

      - name: Build Ubuntu
        shell: bash
        if: matrix.os == 'ubuntu-20.04'
        working-directory: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}
        run: cmake --build . --config $BUILD_TYPE --target Editor -- -j

      - name: Build MacOS
        shell: bash
        if: matrix.os == 'macos-latest'
        working-directory: ${{github.workspace}}/cmake_build_${{ matrix.build_type }}
        run: cmake --build . --config $BUILD_TYPE --target Editor -- -j
