name: Debricked Vulnerability scan

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: snickerbockers/submodules-init@v4

      - name: Clone PhysFS
        run: |
          hg clone https://hg.icculus.org/icculus/physfs/ ext/physfs

      - name: Apply Patches
        shell: bash
        run: |
          git apply --apply patches/glad.patch
          git apply --apply patches/ctti.patch
          git apply --apply patches/fmt.patch

      - uses: debricked/actions/scan@v1
        env:
          USERNAME: ${{ secrets.DEBRICKED_USERNAME }}
          PASSWORD: ${{ secrets.DEBRICKED_PASSWORD }}
          UPLOAD_ALL_FILES: "true"
