on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snickerbockers/submodules-init@v4

      - name: Clone PhysFS
        run: |
          hg clone https://hg.icculus.org/icculus/physfs/ ext/physfs

      - name: Apply Patches
        shell: bash
        run: git apply --apply patches/ctti.patch && git apply --apply patches/glad.patch

      - uses: returntocorp/semgrep-action@v1
        with:
          auditOn: push
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 1238