name: SonarCloud
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
      BUILD_DIR: ${{github.workspace}}/cmake_build_debug
    steps:
      - uses: BSFishy/pip-action@v1
        with:
          packages: Jinja2<3.0

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install xorg-dev clang

      - uses: actions/checkout@v2
      - uses: ./.github/actions/prepare-external-action

      - name: Create Build Environment
        shell: bash
        run: |
          cmake -E make_directory $BUILD_DIR

      - name: Configure CMake
        shell: bash
        env:
          CC: /usr/bin/clang
          CXX: /usr/bin/clang++
        working-directory: ${{github.workspace}}/cmake_build_debug
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_FLAGS=-fpermissive -DBUILD_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
